### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by enyciaa** [enyciaa/CrowdScoresTest#1]
- [x] Sort data
- [x] Add methods for yesterday and tomorrow
- [x] Add toolbar with selectable data
- [x] Style close to CrowdScores
- [x] Fix recycler list
